cmake/config.cmake
Turn on RPATH's on OS/X unconditionally. This should give more UNIX-like behavior as far as libraries that Just Work, path-wise, from a build directory. More to the point, it silences a warning when using newer versions of CMake which default to this behavior. (We could also bump the minimum required CMake version, but we like backward compatibility, and for now, this doesn't seem like sufficient reason to start requiring 3.x.)
=> Use RPATH on OS/X

CMakeLists.txt, cmake/functions.cmake
Refactor how we install our includes (headers), as `PUBLIC_HEADER` unfortunately strips subdirectories. Also, fix an error in the regular expression used to check for a trailing slash that was causing invalid interface include directories to be set on our exported library target.
@mleotta, can you test if this fixes the [MAP-Tk](https://github.com/kitware/maptk) CI problem? (Or does it need to be merged first?)
=> Fix bugs installing includes

cmake/modules/UseQtExtensions.cmake
Modify `qte_amc_wrap_ui` to set the environment (`PATH`, specifically) when running `qte-amc` on Windows, when sufficiently new CMake is used. This should make it easier to build, since running `qte-amc`, which is normally done at build time by projects using it, requires that the Qt libraries are in the library path.
=> Set environment when running qte-amc

cmake/modules/UseQtExtensions.cmake
OS X has a similar problem to Windows in that Qt or its dependencies may
not be found when running qte-amc.  Generally this can be fixed by
setting DYLD_FALLBACK_LIBRARY_PATH.  The problem arises on OS X 10.11
(El Capitan) and above in which the system integrity protection feature
clears the DYLD_* environment variables.  This patch uses a similar
trick already applied for Windows to set the environment before calling
qte-amc.
=> Wrap qte-amc for a custom environment on OS X

cmake/config.cmake
If CMAKE_CXX_FLAGS is not set, string(REPLACE) complains that there
are not enough arguments. This commit fixes the issue by forcing a
fourth argument, even if it's an empty string.
=> Fix string(REPLACE) call for CMAKE_CXX_FLAGS

core/qtGet.h
Exclude safety overload when building on GCC 4.8, which has broken overload resolution in the face of r-value references.
There are three overloads of `qtGet`; one each for `const` and non-`const` references, and a safety overload for temporaries, which is explicitly deleted in order to prevent users calling `qtGet` on a temporary, which would lead to a dangling reference. Unfortunately, the latter confuses the broken overload resolution in GCC 4.8 (GCC 4.9 and later do not have this bug). However, since it is only a safety mechanism to prevent users from doing something wrong, it is not called by correct code. Thus, it is feasible to omit this overload when building with GCC 4.8; such users will just lose out on being prevented from writing broken code.
=> Fix broken qtGet overload resolution on GCC 4.8

CMakeLists.txt, util/qtColorScheme.cpp, util/qtColorScheme.h
Create new class `qtColorScheme`, which is useful for assisting consumers with implementing theming support (i.e. the ability to load a custom color scheme from a file).
=> Add theming support helpers

CMakeLists.txt, tests/CMakeLists.txt, tests/TestNaturalSort.cpp, util/qtNaturalSort.cpp, util/qtNaturalSort.h
Add an implementation of "natural" sorting. The objective is to be able to "naturally" sort strings which contain numbers, e.g. to sort "x5" before "x22". This handles [non-ASCII digits](https://www.fileformat.info/info/unicode/category/Nd/list.htm) as well as numbers of any length. However, it has inevitable limitations, which are described in the documentation.
For now, sorting of non-numeric potions is strictly lexicographical. Case insensitivity or locale-aware sorting may be added at some point in the future. (The comparator is set up as a functor rather than a function in order to facilitate this possibility in a hopefully source compatible manner.)
=> Implement natural sorting

cmake/config.cmake, core/qtGlobal.h
Request that VS not lie about `__cplusplus`. Don't redefine built-in keywords (even though the way we were doing so is likely safe, it makes VS grumpy).
=> More VS fixes

CMakeLists.txt, designer/qtDesignerWidgetInterface.h
So... apparently, the "correct" way of building plugins for Designer changed in Qt5, and, while an attempt was made to preserve compatibility so that the Qt4 method would still work, it turns out it doesn't, for some reason, on macOS.
Fortunately, it appears that porting to the new mechanism is possible. Accordingly, adjust the include header to be the minimum needed header (which is also the correct header for "the new way"), and adjust the link libraries for the plugin so that a) including this header works for both Qt4 and Qt5 and b) we avoid the broken shim header when building against Qt5.
See also https://bugreports.qt.io/browse/QTBUG-73500.
=> Fix build of Designer plugin on macOS

CMakeLists.txt, cmake/config.cmake
Use `add_compile_options` instead of directly manipulating `CXX_FLAGS`. Export requirement to tell MSVC to not lie about its C++ version support. Set required flags on the header-only interface target instead of the full library target (the latter will still get them transitively, but the former also needs them).
Fixes #20. @mleotta and/or @RustyBlue, please test and report back; thanks!
=> Improve handling of compile options

cmake/modules/UseQtExtensions.cmake
This is needed on Linux for the same reason as on other platforms.
We need to set the library path so that qte-amc can find the Qt libraries
when used in a build process.
=> Set the QTE_AMC_ENVIRONMENT for Linux as well as Win32 and Apple

util/qtUiState.cpp, util/qtUiState.h
Add a new overload of `qtUiState::mapState` to persist the state of a `QHeaderView`. This allows persisting state of e.g. `QTreeView`. (The part that is interesting to persist is the column sizes and sort order, which is accomplished via the `QHeaderView`.)
=> Add persistence of QHeaderView state

cmake/qtExtensionsConfig.cmake.in
Since a432e9a14c8b, we provide helper macros that introduce a new mechanism for adding meta-information. Unfortunately, CMake's AUTOMOC does not recognize these out of the box, such that headers that use only these helpers are not processed. Modify our configuration so that our users will automatically have the key macro added to the set of macros that CMake checks when deciding to run AUTOMOC on a header.
=> Improve AUTOMOC with qtExtensions

widgets/qtThrobber.cpp, widgets/qtThrobber.h
Add ability to paint a translucent background to `qtThrobber`, which is useful when using it as an overlay on another widget. Add (limited) ability to change the throbber colors. Slightly tweak the default colors.
=> Improve qtThrobber

util/qtColorScheme.cpp
Add additional color roles to `qtColorScheme`'s ability to save and restore palettes.
=> Improve qtColorScheme

cmake/qtExtensionsConfig.cmake.in
Modify our package configuration to also search for Qt. This will make it easier for consumers to use us; in particular, without having to know the list of what components we need.
=> Better export dependency on Qt

CMakeLists.txt, cmake/depends-qt5.cmake, cmake/testing.cmake, designer/qtDesignerPlugin.cpp, designer/qtSvgWidgetInterface.h, tests/CMakeLists.txt, tests/TestSvgWidget.cpp, widgets/qtSvgWidget.cpp, widgets/qtSvgWidget.h
Create a simple widget to render an SVG. Unlike loading an SVG into a QLabel, this supports resizing while still rendering at display resolution (unlike QLabel, which renders to a pixmap once and then resizes that), and unlike QSvgWidget, this supports changing the position of the SVG within the widget.
Note that animation is not currently supported.
=> Add simple SVG widget

itemviews/qtComboBoxDelegate.cpp, itemviews/qtComboBoxDelegate.h
See commit log for details. Short version: fix a bug where the popup would be shown and immediately hidden due to how `QComboBox` handles mouse events.
=> Fix combobox delegate popup

core/qtUtil.cpp, core/qtUtil.h
Update style for `qtUtil`. Create a new function in qtUtil to set the icon theme.
See documentation thereof for rationale. Additionally, due to an apparent Qt bug, getting the name of the system theme requires a nasty work-around that involves asking GTK(!), which makes it much more unreasonable for individual applications to have to do this themselves.
=> Add function to set icon theme

dom/qtDom.cpp, tests/TestNaturalSort.cpp, util/qtColorScheme.cpp
Fix qtColorScheme for Qt < 5.12. *Do* use deprecated QString::split, as the new signature doesn't exist until Qt 5.14.
=> Fix build for Qt < 5.12
